# Generated by Django 5.0.3 on 2024-03-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_video_favoritevideos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteVideos',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
