# Generated by Django 5.0.3 on 2024-05-17 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_model',
            name='Audio',
            field=models.FileField(upload_to='Audios/'),
        ),
        migrations.AlterField(
            model_name='audio_model',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this Audio, generated automatically.', primary_key=True, serialize=False),
        ),
    ]
