# Generated by Django 5.0.3 on 2024-05-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_Fav',
            field=models.BooleanField(default=False),
        ),
    ]
